name: Rust

on:
  push:
    branches: [ main, dev, cicd ]
  pull_request:
    branches: [ main ]

env:
  CARGO_TERM_COLOR: always

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - name: Install toolchain
        uses: actions-rs/toolchain@v1
        with:
            toolchain: stable
            components: rustfmt
      - name: Build
        uses: actions-rs/cargo@v1
        with:
          command: build
          args: --release --all-features
