name: Rust

on:
  push:
    branches: [ main, dev ]
  pull_request:
    branches: [ main ]

env:
  CARGO_TERM_COLOR: always

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
      - name: Install latest nightly
        uses: actions-rs/toolchain@v1
        with:
            toolchain: stable
            components: rustfmt

      - name: Run cargo check
        uses: actions-rs/cargo@v1
        with:
          command: check
      - name: Build
      - uses: actions-rs/cargo@v1
        with:
          command: build
          args: --release --all-features
